FROM python:3.8-slim

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Prague

ENTRYPOINT ["/root/start.sh"]

RUN apt-get update \
    && apt-get install -y tzdata python3-pip python-is-python3 git ffmpeg

RUN pip install --upgrade pip

COPY python/era_5g_object_detection_common /root/era_5g_object_detection_common

RUN cd /root/era_5g_object_detection_common \
    && pip3 install -r requirements.txt \
    && pip3 install . 

COPY python/era_5g_object_detection_distributed_interface /root/era_5g_object_detection_distributed_interface

RUN cd /root/era_5g_object_detection_distributed_interface \
    && pip3 install -r requirements.txt \
    && pip3 install . 

COPY docker/era_5g_object_detection_distributed/start_interface.sh /root/start.sh

RUN chmod +x /root/start.sh

EXPOSE 5896

