FROM but5gera/netapp_base_mmcv_cpu:0.2.0

COPY python/era_5g_object_detection_common /root/era_5g_object_detection_common

RUN cd /root/era_5g_object_detection_common \
    && pip3 install -r requirements.txt \
    && pip3 install . 

COPY python/era_5g_object_detection_distributed_worker /root/era_5g_object_detection_distributed_worker

RUN cd /root/era_5g_object_detection_distributed_worker \
    && pip3 install -r requirements.txt \
    && pip3 install . 

RUN useradd  --create-home --shell /bin/bash newuser

COPY docker/era_5g_object_detection_distributed/start_worker.sh /home/newuser/start.sh

RUN chown newuser /home/newuser/start.sh

USER newuser
WORKDIR /home/newuser


RUN chmod +x /home/newuser/start.sh

ENTRYPOINT ["/home/newuser/start.sh"]

ENV NETAPP_MODEL_VARIANT=yolov3_mobilenet
ENV NETAPP_TORCH_DEVICE=cpu
ENV NETAPP_MMDET_PATH=/home/newuser/mmdetection/


	
